### ISSUE TITLE
虚心的请教咨询个问题tmock

### ISSUE THREAD

**Issue by git45016683** [zhangyuyu/learn-golang#1]
博主，你好。
我在的blog[单元测试成神之路——C++篇](https://zhangyuyu.github.io/cpp-unit-test/)中看到最后你有提到一个tmock的mock框架。但我搜索不到这个tmock的框架，想要请教一下，tmock这个框架可以从哪里下到/买到之类的？可否提供个链接，让我深入了解下？因为我现在在使用gmock进行单元测试，一些普通的非虚成员函数的确令我不太爽(现在是用stub模拟调用返回，但不能很好的鉴别期望调用的次数等)。
希望能得到回答，很抱歉以这种方式联系您。但我没instagram，GitHub也不能留言。。。只能从这里给你留个言。

**Comment by zhangyuyu** [comment]
这里的tmock是公司内部的一个封装脚本，主要是用了hook+mock的技术方案，摆脱了gmock对多态、注入机制的依赖。其中hook技术主要完成mock类函数替换，通过向mock类函数传递参数控制其行为。不好意思，这里不太方便share源码。

根据之前的调研，如果想达到的你的要求，需要对现有的代码做一些改造，不然确实只能用stub方式了。


Thanks,



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhangyuyu/learn-golang"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月16日(星期三) 下午4:09
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[zhangyuyu/learn-golang] 虚心的请教咨询个问题tmock (Issue #1)





 
博主，你好。
 我在的blog单元测试成神之路——C++篇中看到最后你有提到一个tmock的mock框架。但我搜索不到这个tmock的框架，想要请教一下，tmock这个框架可以从哪里下到/买到之类的？可否提供个链接，让我深入了解下？因为我现在在使用gmock进行单元测试，一些普通的非虚成员函数的确令我不太爽(现在是用stub模拟调用返回，但不能很好的鉴别期望调用的次数等)。
 希望能得到回答，很抱歉以这种方式联系您。但我没instagram，GitHub也不能留言。。。只能从这里给你留个言。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by git45016683** [comment]
了解了。thanks.
